### ISSUE TITLE
Probar la biblioteca Rubix

### ISSUE THREAD

**Issue by RaquelSancha** [RaquelSancha/GII_O_MA_20.04#46]
Probar la biblioteca machine learning Rubix para usarla en la predicción de datos.

**Comment by clopezno** [comment]
@RaquelSancha cuando añadas los código de prueba de la biblioteca al repositorio  con un commit  añade el identificador de la tarea  #46 en el texto descriptivo del commit. De esta forma podremos trazar los cambios en el código asociados a la incidencia.
