### ISSUE TITLE
Subir la app a Heroku

### ISSUE THREAD

**Issue by RaquelSancha** [RaquelSancha/GII_O_MA_20.04#53]

**Comment by clopezno** [comment]
Raquel ¿Cuál es la url de acceso a la WebApp en Heroku?
Saludos

**Comment by RaquelSancha** [comment]
Es esta https://coyunturaeconomica2.herokuapp.com/ también os he añadido a todos como colaboradores en heroku.

**Comment by RaquelSancha** [comment]
Para probar la app:
Usuario: superadmin@superadmin.es
Contraseña: superadmin

**Comment by clopezno** [comment]
He probado el acceso y funciona. Seguro que añadiendo en tu proceso de desarrollo el despliegue continuo de la Web App en Heroku permite valorar mejor las nuevas funcionalidades que incorpores tanto a Bruno como a Santiago.
Buen trabajo Raquel.

**Comment by bbaruque** [comment]
A mi también me funciona la WebApp y el acceso de usuario superadmin.
¡Perfecto Raquel!
