### ISSUE TITLE
Opción para importar datos desde Excel

### ISSUE THREAD

**Issue by RaquelSancha** [RaquelSancha/GII_O_MA_20.04#57]

**Comment by clopezno** [comment]
Raquel ¿cuál es el motivo de que no funcione la importación desde Excel? Reabro la tarea para que justifiques el motivo.

**Comment by RaquelSancha** [comment]
> Raquel ¿cuál es el motivo de que no funcione la importación desde Excel? Reabro la tarea para que justifiques el motivo.

No es que no funcione, es que no me da tiempo a implementarlo y he dado prioridad a otras tareas. Por eso le he puesto la etiqueta wontfix indicando que no voy a trabajar en esto.
