### ISSUE TITLE
Programar vista de los datos

### ISSUE THREAD

**Issue by RaquelSancha** [RaquelSancha/GII_O_MA_20.04#82]
Realizar la interfaz de usuario correspondiente a la estimación de los datos.  Se mostrarán los datos estimados en una tabla.

**Comment by clopezno** [comment]
Usar el campo descripción de la issue para facilitar la comprensión de la tarea. Si se realiza este tipo de documentación ayudaré a la hora de cerar los anexos de planificación y de especificación de requisitos.
