### ISSUE TITLE
Elegir estimador de datos

### ISSUE THREAD

**Issue by RaquelSancha** [RaquelSancha/GII_O_MA_20.04#83]
Elegir el estimador de datos para su predicción de entre los posibles de la biblioteca Rubix. Cada estimador predice los datos de una manera diferente.

**Comment by clopezno** [comment]
Sugiero mejorar  la descripción de la tarea.
Me surge una duda:
- Si la issue está etiquetad como desarrollo ¿no debería tener algún commit asociado?

**Comment by RaquelSancha** [comment]
> Sugiero mejorar la descripción de la tarea.
> Me surge una duda:
> 
> * Si la issue está etiquetad como desarrollo ¿no debería tener algún commit asociado?

Ahora cambio la etiqueta porque no define bien la issue.
