### ISSUE TITLE
Descargar Laravel

### ISSUE THREAD

**Issue by RaquelSancha** [RaquelSancha/GII_O_MA_20.04#9]

**Comment by clopezno** [comment]
¿Para qué se vuelve a reabrir esta tarea?

**Comment by RaquelSancha** [comment]
> ¿Para qué se vuelve a reabrir esta tarea?

Porque no tenía una estimación puesta y entonces no me dejaba meterla en el gráfico burn down.  He tenido que volverla a abrir, ponerle una duración y luego volverla a cerrar.

**Comment by clopezno** [comment]
No te preocupes por lo que no hiciste en otros sprints. Creo que es mejor  mirar hacia delante y realizar bien lo que queda  por hacer: incrementos  de funcionalidad, pruebas de requisitos, revisiones documentación, pruebas de aceptación de los tutores...
La idea de introducir las issues en Github es para que ayuden a comprender e interpretar el  proceso de desarrollo seguido durante el proyecto. No consiste en abrir y cerrar issues sin describir, sin diálogo  o sin enlazar con cambios de otros documentos del repositorio.
