### ISSUE TITLE
Comparar datos reales con la predicción de los datos

### ISSUE THREAD

**Issue by RaquelSancha** [RaquelSancha/GII_O_MA_20.04#96]
Hacer una prueba prediciendo datos que ya tengo y comparar los datos reales con los predichos en un gráfico.

**Comment by clopezno** [comment]
Creo que hay refactorizar la función prueba. 
Primero el nombre no es apropiado y además hay que dividir en varias funciones: por lo menos separa entrenamiento de predicción.
